Guard mocked grpc with mutex, to prevent parallel access
Otherwise, it causes crash of mocked core with:
fatal error: concurrent map read and map write

goroutine 65189 [running]:
internal/runtime/maps.fatal({0xd93b64?, 0x47d4be?})
        /usr/local/go/src/runtime/panic.go:1046 +0x18
github.com/NVIDIA/infra-controller-rest/site-workflow/pkg/grpc/server.(*NICoServerImpl).FindTenantKeysetsByIds(0xc0001a7b80, {0xc000a0ee60?, 0xc00010c920?}, 0xc000a0ee60)
        /workspace/site-workflow/pkg/grpc/server/nico_test_server.go:1174 +0xbf
<skipped>